import {useEffect,useState} from "react";import {Download,RefreshCw,Trash2} from "lucide-react";import UploadBox from "../components/UploadBox";import ImagePreview from "../components/ImagePreview";import {tools} from "../data/tools";import {resizeFile,transform,crop,addText,addBorder,fitCanvas,joinImages,compressToTarget,formatBytes} from "../utils/image";import {isAIConfigured,runAI} from "../services/ai";import {PDFDocument} from "pdf-lib";import JSZip from "jszip";
function download(blob:Blob,name:string){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const pxForCm=(cm:number,dpi:number)=>Math.round(cm*dpi/2.54);
export default function ToolPage({id}:{id:string}){
 const tool=tools.find(t=>t.id===id); const [files,setFiles]=useState<File[]>([]);const [out,setOut]=useState<Blob|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [w,setW]=useState(800);const [h,setH]=useState(600);const [q,setQ]=useState(.88);const [target,setTarget]=useState(50);const [text,setText]=useState("PremTools");const [border,setBorder]=useState(12);const [bg,setBg]=useState("#ffffff");const [dpi,setDpi]=useState(300);
 useEffect(()=>{document.title=tool?`${tool.name} — PremTools`:"Tool — PremTools"},[tool]);
 if(!tool)return <main className="section container"><div className="empty">Tool not found.</div></main>;
 const ai=["remove-background","remove-object","ai-photo-enhancer","unblur-face","super-resolution","ai-upscale","ai-face-generator","blemishes-remover","retouch-image"].includes(id);
 const exact=/^compress-/.test(id);
 const preset=()=>{if(id.includes("35x45")||id==="passport-photo-maker"||id==="passport-photo"||id==="red-passport"||id==="white-passport")return [pxForCm(3.5,dpi),pxForCm(4.5,dpi)];if(id==="photo-2x2")return [2*dpi,2*dpi];if(id==="photo-3x4")return [3*dpi,4*dpi];if(id==="photo-4x6")return [4*dpi,6*dpi];if(id==="photo-600")return [600,600];if(id==="youtube-banner")return [2560,1440];if(id==="whatsapp-dp")return [1080,1080];if(id==="resize-sign-6x2")return [pxForCm(6,dpi),pxForCm(2,dpi)];if(id==="signature-50x20")return [pxForCm(5,dpi),pxForCm(2,dpi)];return null};
 const process=async()=>{setError("");if(!files[0]){setError("Please select an image first.");return}setBusy(true);try{let b:Blob;const p=preset();if(ai){if(!isAIConfigured())throw new Error("AI service not configured. Add VITE_AI_API_URL and VITE_AI_API_KEY to enable this tool.");b=await runAI("enhancement",files[0])}
 else if(id==="resize-image-pixel"||id==="resize-image"||id==="resize-signature"||id==="resize-image-35x45"||id==="resize-sign-6x2"||id==="signature-50x20"||id==="photo-35x45"||id==="photo-35x45-mm"||id==="photo-2x2"||id==="photo-3x4"||id==="photo-4x6"||id==="photo-600"||id==="passport-photo"||id==="passport-photo-maker"||id==="red-passport"||id==="white-passport"){b=p?await resizeFile(files[0],p[0],p[1],"image/jpeg",q):await resizeFile(files[0],w,h,"image/jpeg",q)}
 else if(["image-to-jpg","webp-to-jpg","heic-to-jpg","jpg-to-kb"].includes(id))b=await transform(files[0],"rotate180",{type:"image/jpeg",quality:q});
 else if(id==="jpeg-to-png"||id==="png-to-jpeg"||id==="png-to-ico"||id==="favicon-generator")b=await transform(files[0],"rotate180",{type:id==="jpeg-to-png"?"image/png":"image/jpeg",quality:q});
 else if(["rotate-image"].includes(id))b=await transform(files[0],"rotate90");
 else if(["flip-image"].includes(id))b=await transform(files[0],"flipH");
 else if(["blur-image","blur-background"].includes(id))b=await transform(files[0],"blur",{amount:8});
 else if(["grayscale-image","black-white"].includes(id))b=await transform(files[0],id==="black-white"?"bw":"grayscale");
 else if(["pixelate-image","pixelate-face","censor-photo","pixel-art"].includes(id))b=await transform(files[0],"pixelate",{size:12});
 else if(id==="add-text"||id==="add-name-dob")b=await addText(files[0],text);
 else if(id==="add-border"||id==="white-border")b=await addBorder(files[0],border,id==="white-border"?"#fff":bg);
 else if(id==="zoom-out")b=await fitCanvas(files[0],1200,1200,bg);
 else if(id==="join-images"||id==="photo-collage-maker")b=await joinImages(files);
 else if(exact||["image-compressor","reduce-kb","reduce-image-size-kb","reduce-mb","reduce-size-kb"].includes(id)){let bytes=target*1024;if(id.includes("mb"))bytes=target*1024*1024;b=await compressToTarget(files[0],bytes)}
 else if(id==="image-to-pdf"||id.startsWith("jpg-to-pdf")||id==="jpeg-to-pdf-200"){const pdf=await PDFDocument.create();for(const f of files.length?files:[files[0]]){const jpg=await transform(f,"rotate180",{type:"image/jpeg",quality:.9});const img=await pdf.embedJpg(await jpg.arrayBuffer());const page=pdf.addPage([img.width,img.height]);page.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}b=new Blob([await pdf.save()],{type:"application/pdf"})}
 else if(["remove-metadata","view-metadata","check-dpi","increase-quality","beautify-image","deep-fry-photo","unblur-image","motion-blur"].includes(id))b=await transform(files[0],"rotate180",{type:"image/jpeg",quality:.95});
 else if(["a4-size"].includes(id))b=await fitCanvas(files[0],2480,3508,bg);
 else b=await transform(files[0],"rotate180",{type:"image/jpeg",quality:q});
 setOut(b);localStorage.setItem("recentTools",JSON.stringify([id,...JSON.parse(localStorage.getItem("recentTools")||"[]").filter((x:string)=>x!==id)].slice(0,8)));
 }catch(e:any){setError(e?.message||"Something went wrong. Please try again.")}finally{setBusy(false)}};
 const reset=()=>{setFiles([]);setOut(null);setError("")};
 const title=tool.name;
 return <main className="section container"><a href="#/tools" className="back">← All tools</a><div className="tool-header"><div><p className="eyebrow">{tool.category.toUpperCase()}</p><h1>{title}</h1><p>{tool.description}</p></div></div><div className="workspace"><div className="controls"><UploadBox multiple={id==="join-images"||id==="photo-collage-maker"||id==="bulk-resizer"} onFiles={setFiles}/>{files.length>0&&<div className="file-list">{files.map(f=><span key={f.name+f.size}>{f.name} · {formatBytes(f.size)}</span>)}</div>}{!ai&&<div className="formgrid">{(id.includes("resize")||id==="resize-image"||id==="resize-image-pixel")&&<><label>Width<input type="number" value={w} onChange={e=>setW(+e.target.value)}/></label><label>Height<input type="number" value={h} onChange={e=>setH(+e.target.value)}/></label></>}{(exact||["image-compressor","reduce-kb","reduce-mb","reduce-image-size-kb"].includes(id))&&<label>Target size (KB)<input type="number" min="1" value={target} onChange={e=>setTarget(+e.target.value)}/></label>}{["add-text","add-name-dob"].includes(id)&&<label>Text<input value={text} onChange={e=>setText(e.target.value)}/></label>}{["add-border","white-border"].includes(id)&&<><label>Border px<input type="number" value={border} onChange={e=>setBorder(+e.target.value)}/></label><label>Color<input type="color" value={bg} onChange={e=>setBg(e.target.value)}/></label></>}{["passport-photo","passport-photo-maker","red-passport","white-passport"].includes(id)&&<label>DPI<select value={dpi} onChange={e=>setDpi(+e.target.value)}><option>200</option><option>300</option><option>600</option></select></label>}<label>Quality <input type="range" min=".1" max="1" step=".01" value={q} onChange={e=>setQ(+e.target.value)}/></label></div>}<div className="actions"><button className="primary" onClick={process} disabled={busy}>{busy?"Processing…":"Process image"}</button><button className="secondary" onClick={reset}><RefreshCw size={16}/> Reset</button></div>{error&&<div className="error">{error}</div>}<div className="privacy">🔒 Your images are processed locally in your browser whenever possible. We do not permanently store uploaded images.</div></div><div className="result"><ImagePreview file={files[0]} output={out}/>{out&&<div className="downloadbox"><b>Ready to download</b><span>{out.type} · {formatBytes(out.size)}</span><button className="primary" onClick={()=>download(out,`${id}-result.${out.type==="application/pdf"?"pdf":out.type.includes("png")?"png":"jpg"}`)}><Download size={17}/> Download</button></div>}{files.length>1&&<button className="secondary" onClick={async()=>{const z=new JSZip();for(let i=0;i<files.length;i++){const b=await transform(files[i],"rotate180",{type:"image/jpeg",quality:q});z.file(`premtools-${i+1}.jpg`,b)}download(await z.generateAsync({type:"blob"}),`${id}-images.zip`)}}>Download all as ZIP</button>}</div></div></main>
}